sudo: false

language: python

env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels

cache:
  directories:
    - ~/.cache/pip

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - python-pytest

python:
  - 2.7
  - 3.5

before_install:
  - pip install pip setuptools --upgrade

install:
  - CC=g++-5 pip install .\[tests\] --upgrade

script:
  - py.test ais test --cov=ais --cov-report term-missing
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then (cd src && CC=gcc-5 CXX=g++-5 make -f Makefile-custom -j 4 test); fi
